spring:
  config:
    import: optional:classpath:quizup-defaults.yml
  application:
    name: quizup-social
  profiles:
    default: local

  flyway:
    locations: classpath:db/migration/social

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

microservice:
  swagger:
    description: QuizUp Social Module - Topic and player follows, and 1v1 challenges


